2025-09-03 11:52:35 - auth - INFO - Getting auth token for RZN1 service...
2025-09-03 11:52:36 - auth - ERROR - Error getting auth token for rzn1: HTTPSConnectionPool(host='rzn1.com', port=443): Max retries exceeded with url: /auth/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x72af62dbac30>: Failed to resolve 'rzn1.com' ([Errno -2] Name or service not known)"))
2025-09-03 11:55:04 - auth - INFO - Getting auth token for RZN1 service...
2025-09-03 11:55:05 - auth - ERROR - Error getting auth token for rzn1: 404 Client Error: Not Found for url: https://rzn1-be.stockone.com/None
2025-09-03 12:00:49 - auth - INFO - Getting auth token for RZN1 service...
2025-09-03 12:00:51 - auth - ERROR - Error getting auth token for rzn1: 404 Client Error: Not Found for url: https://rzn1-be.stockone.com/None
2025-09-03 12:03:40 - auth - INFO - Getting auth token for RZN1 service...
2025-09-03 12:03:40 - auth - INFO - Using auth URL: https://rzn1-be.stockone.com/None
2025-09-03 12:03:41 - auth - ERROR - Error getting auth token for rzn1: 404 Client Error: Not Found for url: https://rzn1-be.stockone.com/None
2025-09-03 12:03:41 - auth - ERROR - Failed to get tokens: 404 Client Error: Not Found for url: https://rzn1-be.stockone.com/None
2025-09-03 12:04:25 - auth - INFO - Getting auth token for RZN1 service...
2025-09-03 12:04:25 - auth - INFO - Using auth URL: https://rzn1-be.stockone.com/None
2025-09-03 12:05:29 - auth - ERROR - Failed to get tokens: 
2025-09-03 12:05:31 - auth - INFO - Getting auth token for RZN1 service...
2025-09-03 12:05:31 - auth - INFO - Using auth URL: https://rzn1-be.stockone.com/o/token/
2025-09-03 12:05:59 - auth - INFO - Successfully obtained token for RZN1
2025-09-03 12:05:59 - auth - INFO - Successfully obtained token for RZN1 service
